//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteczka.Data.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApteczkaDbEntities : DbContext
    {
        public ApteczkaDbEntities()
            : base("name=ApteczkaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APTCures> APTCures { get; set; }
        public virtual DbSet<APTLocation> APTLocation { get; set; }
        public virtual DbSet<APTPharmacy> APTPharmacy { get; set; }
        public virtual DbSet<APTPharmacyCures> APTPharmacyCures { get; set; }
        public virtual DbSet<APTUsers> APTUsers { get; set; }
    }
}
