//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteczka.Data.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTLocation
    {
        public long Id { get; set; }
        public long APTPharmacyId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        public virtual APTPharmacy APTPharmacy { get; set; }
    }
}
