//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteczka.Data.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTLocationCures
    {
        public long Id { get; set; }
        public long APTLocationId { get; set; }
        public long APTCuresId { get; set; }
    
        public virtual APTCures APTCures { get; set; }
        public virtual APTLocation APTLocation { get; set; }
    }
}
