//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteczka.Data.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APTLocation()
        {
            this.APTLocationCures = new HashSet<APTLocationCures>();
        }
    
        public long Id { get; set; }
        public long APTPharmacyId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        public virtual APTPharmacy APTPharmacy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTLocationCures> APTLocationCures { get; set; }
    }
}
