//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteczka.Data.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTPharmacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APTPharmacy()
        {
            this.APTLocation = new HashSet<APTLocation>();
            this.APTPharmacyCures = new HashSet<APTPharmacyCures>();
        }
    
        public long Id { get; set; }
        public long APTUserId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTLocation> APTLocation { get; set; }
        public virtual APTUsers APTUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTPharmacyCures> APTPharmacyCures { get; set; }
    }
}
